<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<SupportedOSPlatform>windows</SupportedOSPlatform>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CapDeviceLib" Version="1.0.1" />
		<PackageReference Include="GETT_DisplayDeviceLib" Version="1.0.0" />
		<PackageReference Include="Peakboard.ExtensionKit" Version="4.0.1" PrivateAssets="false" ExcludeAssets="runtime" />
		<PackageReference Include="System.Management" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Extension.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Remove="pb_datasource_gett.png" />
		<EmbeddedResource Include="pb_datasource_gett.png" />
	</ItemGroup>

</Project>